---
- hosts: workstation

  tasks:
    - name: install android-file-transfer
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - android-file-transfer
      sudo: no
