---
- hosts: workstation

  tasks:
    - name: command-line-tools-brew
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - bash-completion
        - imagemagick
        - autojump
      sudo: no
    - name: command-line-tools-cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - the-unarchiver
      sudo: no
