---
- hosts: workstation

  tasks:
    - name: command-line-tools-brew
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - bash-completion
        - imagemagick
        - autojump
        - zsh
        - tmux
        - gphoto2
        - git
        - git-flow
        - jq
      sudo: no
    - name: command-line-tools-cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - the-unarchiver
      sudo: no
