---
- hosts: workstation

  tasks:
    - name: install Fuse for OSX
      mac_pkg: pkg_name=com.github.osxfuse.pkg.Core pkg_version=2.8.2
               url=http://sourceforge.net/projects/osxfuse/files/osxfuse-2.8.2/osxfuse-2.8.2.dmg/download
               archive_type=dmg archive_path='Install OSXFUSE 2.8.pkg'
      sudo: yes
