---
- hosts: workstation

  tasks:
    - name: install Fuse for OSX
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - osxfuse
        - homebrew/fuse/ext4fuse
      sudo: no
    - name: add user to the operators group
      shell: dscl . append /Groups/operator GroupMembership {{ item }}
      with_items:
        - wouter
      sudo: yes
