---
- hosts: workstation

  tasks:
    - name: install macvim
      homebrew:
        name: macvim
        state: present
      sudo: no

    - name: install janus
      shell: curl -L https://bit.ly/janus-bootstrap | bash
      sudo: no
